JuliaDiff/ChainRulesTestUtils.jl

- README.md
- hopefully this answer "what is this package? why do we need it?"
- in future obviously we need to add actual docs with usage examples
- and decide whether or not this should share docs with ChainRules and ChainRulesCore (probably)
> Add some basic info to README

- Project.toml
- src/ChainRulesTestUtils.jl
Reverting this completely back to the original from `ChainRules/test/test_utils.jl`
> Check that rrule x_ad DNE

- .travis.yml
- Project.toml
- src/ChainRulesTestUtils.jl
- test/runtests.jl
See [ChainRulesCore](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/129) for details
> Tweak API for update

- Project.toml
- src/ChainRulesTestUtils.jl
- src/to_vec.jl
- test/runtests.jl
- test/to_vec.jl
partially closes #24 
I did not do the Composite for structs as that has more open questions about how to do this.
(See #24 for discussion)
> Make Composite{<:Tuple} work

- Project.toml
> Update FiniteDifferences to v0.11

- Project.toml
- src/ChainRulesTestUtils.jl
- src/check_result.jl
- src/iterator.jl
- src/testers.jl
- test/check_result.jl
- test/runtests.jl
- test/testers.jl
This is the much more minimal version of  #57  to just test Inplace accumulation.
This is waiting on me building and metatesting tools to catch the negative cases
This is currently built on top of https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/60/files
I will rebase after that is merged
> Minimal Inplace accumulation testing

- Project.toml
- src/isapprox.jl
- test/isapprox.jl
> Implement isapprox for Composites

- .github/workflows/IntegrationTest.yml
closes #85 
I kind of want to drop a ton of other things from the testing matrix to make more space for these
> make integration tests hit many packages

- .github/workflows/CI.yml
Fixes the cache step for artifacts
> Add Cache Fix

- docs/src/index.md
- src/check_result.jl
- src/testers.jl
- test/testers.jl
a quick paragraph on `check_equal`
> add check_equal docs

- docs/src/index.md
CI link on docs index was still Travis
> update CI link

- Project.toml
- docs/src/index.md
- src/check_result.jl
- src/deprecated.jl
- src/finite_difference_calls.jl
- src/iterator.jl
- src/testers.jl
- test/check_result.jl
- test/deprecated.jl
- test/testers.jl
follow up to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/353
> rename differential types

- Project.toml
- docs/src/index.md
- src/ChainRulesTestUtils.jl
- src/check_result.jl
- src/deprecated.jl
- src/testers.jl
- test/check_result.jl
- test/deprecated.jl
Closes https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/134
idk if i should rename the file they are in also?
> Rename check_equals to test_approx

- Project.toml
- docs/src/index.md
- src/testers.jl
- test/testers.jl
Closes #167 (again)
Cherry picked + version bump so should be good to go, but let's wait for integration tests this time. (should work after https://github.com/JuliaDiff/ChainRules.jl/pull/436)
> Test the number of outputs in `frule` and `rrule` are correct

- Project.toml
- src/testers.jl
- test/testers.jl
Also adds some direct tests for `@maybe_inferred`.
> add support for two-arg `@maybe_inferred`

- Project.toml
- src/ChainRulesTestUtils.jl
- src/check_result.jl
- src/testers.jl
- test/testers.jl
First part of https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/159
Lighter alternative to https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/174, this just runs the pullback to check there is no errors
> Test other tangents

- Project.toml
- docs/Manifest.toml
- test/check_result.jl
- test/testers.jl
Buddy to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/396
needs that merged first
> reorder argument order on InplaceableThunk

- src/rand_tangent.jl
Just removinging some extra new lines
and moving the NoTangent() ones together
> Tidy rand_tangent file

- .github/workflows/CI.yml
see https://github.com/JuliaDiff/ChainRulesCore.jl/pull/519
> Run ci on pushes to main

- Project.toml
- src/rand_tangent.jl
- test/rand_tangent.jl
Motivation is in #234. Note that this PR doesn't solve the described issue completely due to #230, but even by itself should be useful.
> Add rand_tangent() for Broadcasted

- Project.toml
CRC supports Compat 4 in the latest release, seems CRTU is the next package that should be updated.
> Support Compat 4

- docs/src/index.md
- src/testers.jl
> Improve the error message for constructors
