JuliaDiff/ChainRulesTestUtils.jl

.gitignore, .travis.yml, Project.toml, README.md, src/ChainRulesTestUtils.jl, test/runtests.jl
Overview
---
The original discussion for this package stems from [ChainRules.jl #69](https://github.com/JuliaDiff/ChainRules.jl/issues/69). This is an initial port of `test_utils` out of `JuliaDiff/ChainRules.jl`.
This package still needs some work, however after discussing with @oxinabox we want to register this package ASAP. To do so we need to have a `Project.toml` and some structure to the package itself, this PR accomplishes that.
Issues Resolved
---
- #1 
- #5
Future Work
---
After this merge request goes in, we can do the following:
- Register the package
- Write unit tests for this package
- Remove the now duplicate code in [ChainRules.jl](https://github.com/JuliaDiff/ChainRules.jl/blob/master/test/test_util.jl) and use this package as a testing dependency
- Do smaller cleanup …
=> Initial Port from ChainRules.jl

Project.toml, src/ChainRulesTestUtils.jl
I'm in the process of updating [ChainRules.jl](https://github.com/JuliaDiff/ChainRules.jl/) to use this package for testing. While updating it I am running into a couple of warnings and errors:
1) `ChainRulesTestUtils` does not have Test in its dependencies
```
┌ Warning: Package ChainRulesTestUtils does not have Test in its dependencies:
│ - If you have ChainRulesTestUtils checked out for development and have
│   added Test as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ChainRulesTestUtils
└ Loading Test into ChainRulesTestUtils from project dependency, future warnings for ChainRulesTestUtils are suppressed.
```
2) `I` is not defined
```
Error During Test at …
```
=> Added LinearAlgebra and Test to dependencies

src/ChainRulesTestUtils.jl
- Explain that this is basically just `FiniteDifferences.j'vp`
- Doesn't go as far as to justify having it, or why it's written so sneakily 😂
=> Add docstring for `_make_fdm_call`

Project.toml, src/data_generation.jl
<s>We need to remove the random number generation parameter in the generate_well_conditioned_matrix` function to be able to continue with https://github.com/JuliaDiff/ChainRules.jl/issues/180</s>
Create a secondary definition for `generate_well_conditioned_matrix()`
=> Generate well conditioned matrix using Random.GLOBAL_RNG

Project.toml, src/ChainRulesTestUtils.jl, src/data_generation.jl, test/data_generation.jl, test/runtests.jl
```
UndefVarError: Random not defined
Stacktrace:
[1] generate_well_conditioned_matrix(::Int64) at /Users/mattbr/.julia/packages/ChainRulesTestUtils/pVYVF/src/data_generation.jl:7
```
We don't have any tests for `data_generation.jl`, in `0.2.3` I added in a secondary function for `generate_well_conditioned_matrix(N)` which used the `GLOBAL_RNG` from `Random`. It was not defined in this source file and would error out.
I added in some tests for a pre-defined rng and the global one and made the changes so that this code would work.
=> UndefVarError Random not defined in data_generation.jl

Project.toml, src/testers.jl, test/testers.jl
This PR adds a `fkwargs` keyword to the tester functions, which is then splatted as keyword arguments to the tested function `f`.
=> Support testing functions with kwargs

Project.toml, src/testers.jl, test/testers.jl
This fixes #30 by removing the "terrifying" `eval` in `_make_fdm_call`.
=> Remove eval called by rrule_test

Project.toml, src/testers.jl
This PR unifies the two `rrule_test` functions (single-arg and multi-arg). Because the single-arg version checked for approximate equality of outputs, while the multi-arg version iterated over the inputs, this PR partially resolves #29.
=> Unify the two `rrule_test` functions

Project.toml, src/testers.jl, test/testers.jl
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/152
This is now slightly cleaner
We did not have tests that broken because of this, might be good to add some?
OTOH it is now a feature that doesn't exist, there is no longer a special case to test out.
This needs the ChainRulesCore PR to go in first
and then needs it s versions bumped
=> Remove special handling for pullbacks having multiple inputs

Project.toml
I can't think of any problems with doing this here. ChainRules has its own compat that will need to be bumped separately. Locally I've run ChainRules' test suite using FD v0.10.0, and all but one test set pass. But that can be handled in a ChainRules PR.
The rest of #31 will be handled in another PR.
=> Bump compat for FiniteDifferences

Project.toml, src/testers.jl, test/testers.jl
Following https://github.com/JuliaDiff/ChainRules.jl/issues/210, this PR:
- Bumps compat for ChainRulesCore to v0.9
- ~Updates `ChainRulesTestUtils.test_scalar` to conjugate the derivative when testing `rrule`.~ Reimplements `test_scalar` to test entire Jacobian in forward and reverse mode.
- Bumps compat for FiniteDifferences to v0.10 (required for tests of complex functions to consistently work)
=> Follow new complex rule conventions

Project.toml, src/testers.jl, test/testers.jl
`frule_test` currently requires the primal output of `frule` of `f` to be exactly equal to the output of `f`. We previously relaxed this requirement for `rrule_test` (#33), and this PR just uses the same check for `frule_test`.
The ChainRules test suite still passes for me with this change.
=> Check frule primal with isapprox

Project.toml, src/ChainRulesTestUtils.jl, src/generate_tangent.jl, test/generate_tangent.jl, test/runtests.jl
First steps of an implementation to automatically construct appropriate tangent vectors. @oxinabox @sethaxen let me know if you think these are okay as a starting point / if you think that there are any other types that are crucial to have this implemented for.
I would very much like to cover general structs with a generated function, but I've not had a chance to sort that out yet.
=> Automatic tangent generation for simple types

.github/workflows/IntegrationTestChainRules.yml
Usually when I make a change to the testers, I end up locally running the ChainRules test suite to make sure I didn't overlook some edge case. This PR adds the same integration tests that https://github.com/JuliaDiff/ChainRulesCore.jl/pull/193 added to ChainRulesCore.
=> Add ChainRules integration tests

Project.toml, src/testers.jl, test/testers.jl
Currently, the (unenforced) standard is that single-argument functions do not thunk in the pullback. On https://github.com/JuliaDiff/ChainRules.jl/pull/182, @willtebbutt and I were discussing whether we should extend that so that if there is only a single meaningful argument, then that argument's adjoint should not be thunked. This PR takes that opinion and adds a conservative test to `rrule_test`: namely, for functions whose pullbacks only produce one adjoint that is not `DoesNotExist`, that single adjoint is not thunked.
This is more to generate discussion. As you can see in the [integration test](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/runs/863569612?check_suite_focus=true#step:6:1693), several pullbacks in ChainRules break this proposed rule:
- `sum`
- `mean`
- `tr`
- …
=> Check that if only one adjoint exists, it is not thunked

Project.toml, src/ChainRulesTestUtils.jl, src/iterator.jl, test/iterator.jl, test/runtests.jl, test/testers.jl
This PR supersedes https://github.com/JuliaDiff/FiniteDifferences.jl/pull/96 by adding a configurable `TestIterator` that is compatible with FiniteDifferences, `frule_test` and `rrule_test` for the purpose of testing rules defined with iterator primals.
=> Add TestIterator for testing rules with iterator primal inputs

Project.toml, src/testers.jl, test/testers.jl
Adds the same ability for `frule_test` that we currently have for `rrule_test`. Namely, specify a differential for an argument as `nothing` for `frule_test` to make that argument invisible to finite differences. Enables testing of rules for functions like `Symmetric(randn(3, 3), :U)`.
=> Make frule_test work for functions with non-differentiable args

test/meta_testing_tools.jl, test/runtests.jl, test/testers.jl
This PR is about testing that we can actually detect when things are wrong.
The code for `metatest_get_failures` is a pretty nasty hack an on the internals.
I think its clear enough what it is doing.
Two possible alternative implementations:
Julia itself does this to test `@test`.
Writing a test to a file and then kicking it off with ``run(`julia -e file.jl`)``
But three problems are
1. Slow starting an external process is slow
2. Very course grained: all that is easy to test is that it caused julia to to exit with a nonzero status
3. Pretty ugly code, need to redirect stdout still and need to write a file
We could declare a custom testset type which overloads `record` and `finish` so that they don't propate errors upwards.
This might be fiddly, but I have done something like it before in …
=> Test the unhappy path

test/testers.jl
Very small change to tests,
I worked out why we couldn't put iterfun in the testset.
Its because both used the variable `x` and it was creating a closure.
This fixes it b putting the tests that use `x` in a sub-testset
=> Reorganize test for iterfun

test/check_result.jl, test/testers.jl
This is a follow up to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/234
but it doesn't need that PR to be merged first,
as it is a valid test both before and after that change.
The test before was being lazy and once https://github.com/JuliaDiff/ChainRulesCore.jl/pull/234 goes in will start failing
=> Fix tests now that add!! is too smart for them

Project.toml, src/testers.jl, test/testers.jl
This PR makes `frule_test` `deepcopy` all inputs, function kwargs, and tangents before function calls, which enables it to be used to test functions that mutate their inputs. Relates #35.
=> Support testing mutating functions in frule_test

Project.toml, src/check_result.jl, test/check_result.jl
fixed https://github.com/invenia/BlockDiagonals.jl/issues/49
which was overloading `isapprox` to support compare natural and structural differentials
which was broken by https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/57/
I want to do more to support those without them overloading `isapprox`
=> support isapprox still

Project.toml, src/check_result.jl, test/check_result.jl
Follow up from #83 that removes the need for `isapprox` to be defined.
This should be merged *after* #83 
this PR was cut onto of that one and only the last commit is new
=> check_equality on structural x natural

src/check_result.jl, src/testers.jl, test/testers.jl
Closes https://github.com/JuliaDiff/ChainRulesCore.jl/issues/266
There were two issues:
1) missing `;kwargs` causing the wrong method to dispatch
2) finite differencing returns a Tuple for functions which output a Tuple
=> logabsdet test fix

src/testers.jl
[These tests](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/master/test/testers.jl#L250) were failing even after  #87 
CI being broken seems to have let a bunch of stuff slip through
=> Fix rrule test on tuples

.github/workflows/CI.yml
This sets it up so an RSE at Invenia will be notified if nightly build fails
=> Send Invenia Slack Notifications if nightly build fails

src/check_result.jl, src/testers.jl, test/check_result.jl
"behavour" seems to be a typo here, I added a deprecation to avoid breaking external code relying on this
=> rename internal use of  behavour to behaviour

src/testers.jl, test/testers.jl
Fixes https://github.com/JuliaMath/SpecialFunctions.jl/issues/288#issuecomment-749091586
> This is being reported now because of https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/84
> which added checking that the primal type when it was checking if two `Composite{Primal}` were equal.
> but looking at it the code for determining the primal type if the Composite came from FiniteDifferencing is wrong
> https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/92c4888361557f010406aaf14a16240431067915/src/testers.jl#L106-L108
> because it just assumes that that type of the difference is the type of the primal.
> Which it is not for the case for Integers.
> 
> That code was added in https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/89 and …
=> Get primal type from primal when fixing composites

Project.toml, src/testers.jl, test/testers.jl
backporting #93 
for https://github.com/JuliaMath/SpecialFunctions.jl/issues/288#issuecomment-749091586
This has already been reviewed so I am inclided to just merge it if it passes CI
=> backport primal fix

src/testers.jl
This tries to make the errors from this package just a hair less inscrutable. 
Edit: closes #81
=> Improve some errors

Project.toml, src/ChainRulesTestUtils.jl
This PR also sets `max_range` of `_fdm` to `1e-2` to prevent tests from accidentally failing due to singularities.
See also https://github.com/JuliaDiff/ChainRules.jl/pull/341.
=> Increase FiniteDifferences to v0.12

Project.toml, src/testers.jl, test/testers.jl
This PR follows up #78 to only test that `frule`s and `rrule`s are type-stable when the primal itself is type-stable.
=> Only check type-stability of frule and rrule if primal is type-stable

src/ChainRulesTestUtils.jl, src/finite_difference_calls.jl, src/testers.jl
No functional change.
the `tester.jl` file was getting a bit long.
So I moved all the stuff that is about building the exact calls we are making in FiniteDifferences into its own file.
I also reordered so the helper functions are after the main function.
I thought about moving test_scalar into its own file, so that could extract its `Complex` dealing-with branchs into their own helper functions.
But when i saw that the tests were all kind of mixed together i decided not to.
=> Move construction of finite difference calls into own file

.github/workflows/Documenter.yml, Project.toml, docs/src/index.md, src/ChainRulesTestUtils.jl, src/deprecated.jl, src/generate_tangent.jl, src/testers.jl, test/deprecated.jl, test/testers.jl
Closes https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/67
Does option 2D witth `x ⊢ ẋ`
that is `\vdash` + <kbd>tab</kbd>
We can argue about symbols though.
```julia
x = rand(4, 5)
x̄ = rand(4, 5)
ȳ = rand(2, 10)
rrule_test(reshape, ȳ, (x, x̄), ((2, 10), nothing))
rrule_test(reshape, ȳ, (x, x̄), (2, nothing), (10, nothing))
```
No point declaring `x` in advance any-more.
Can just put the `rand` in-place
```julia
test_rrule(reshape, rand(4, 5), (2, 10) ⊢  nothing)
test_rrule(reshape, rand(4, 5), 2  ⊢  nothing, 10 ⊢  nothing)
```
=> Automatically provide tangents

docs/src/index.md, src/testers.jl, test/deprecated.jl, test/meta_testing_tools.jl, test/testers.jl
example output
```julia
julia> test_rrule(two2three, 3.33, -7.77)
Test Summary:                          | Pass  Total
test_rrule: two2three at (3.33, -7.77) |    6      6
Test.DefaultTestSet("test_rrule: two2three at (3.33, -7.77)", Any[Test.DefaultTestSet("Don't thunk only non_zero argument", Any[], 0, false)], 6, false)
````
Closes #121 and #108 
I recomment turning on "hide whitespace changes" when reviewing,
since this indented a ton of code without changing it
---
=> wrap testers in top level testset

test/meta_testing_tools.jl
Julia broke this on current master
https://github.com/JuliaLang/julia/pull/37809#issuecomment-712162789
I am not particularly in a hurry to see this merged.
I don't love this change, since it is now sensitive to the spacing that julia happens to use for `==`
=> stringify orig_expr in meta-metatests

Project.toml, src/generate_tangent.jl, test/generate_tangent.jl
This PR adds support for `BigFloat` to `rand_tangent`. This came up in https://github.com/JuliaStats/StatsFuns.jl/pull/106.
=> Add support for `BigFloat` to `rand_tangent`

Project.toml, docs/src/index.md, src/check_result.jl, src/testers.jl
=> no more `⊢` for types for which rand_tangent gives DoesNotExist

Project.toml, src/testers.jl, test/testers.jl
Closes #112 
I don't think we need a test for this?
=> Better error message when user accidentally passes `Zero()` instead of `DoesNotExist()` in the pullback

Project.toml, src/check_result.jl, test/check_result.jl, test/testers.jl
Currently tests fail since `check_add!!` errors for `Composite`s with a field of type `NotImplemented`: the implementation of `+` for `Composite` in ChainRulesCore uses `elementwise_add` which is implemented with `+` but `+` is not defined for `NotImplemented`.
My suggestion would be to allow operations with `Composite`s with fields of type `NotImplemented` similar to how `muladd` is enabled for `NotImplemented`, i.e., `NotImplemented` wins always, _but_ to not allow general calculations with `+`. This could be achieved by defining
```julia
_add(x, y) = x + y
_add(x::NotImplemented, y) = x
_add(::NotImplemented, y::NotImplemented) = y
_add(x::NotImplemented, ::NotImplemented) = x
```
and using `_add` instead of `+` in `elementwise_add`. I already confirmed that this would fix the test …
=> Enable testing of rules with `@not_implemented`

.github/workflows/Documenter.yml, .gitignore, Project.toml, docs/Manifest.toml, docs/src/index.md, src/testers.jl
This helps with #146 
It doesn't solve it completely.
`test_rrule: muladd on Matrix{ComplexF64},Matrix{ComplexF64},Vector{ComplexF64}:` is still too long.
but it is better than:
```
test_rrule: muladd at (ComplexF64[0.4196589978210228 + 0.06678470996838337im 0.7234983983250549 + 0.12177689554226734im 0.1444667492753262 + 0.852824421053991im; 0.0013063927651701945 + 0.07960169680989404im 0.8821340299832212 + 0.8674832432528303im 0.6399916250104181 + 0.9213673755779661im; 0.9305666542318896 + 0.028798798400179848im 0.3251285135517823 + 0.7192046410325192im 0.781878780061285 + 0.4168105129559001im], ComplexF64[0.9864502766235548 + 0.09411549814329323im 0.568369797143335 + 0.18162232839781756im 0.12073688021595674 + 0.7876976518594212im; 0.3676544278610394 + 0.6476833738007652im …
```
=> Print primal type, not primal value

src/ChainRulesTestUtils.jl, src/check_result.jl, src/output_control.jl, src/testers.jl, test/testers.jl
Combined with the other PRs i have open this should close #146.
We don't nest testsets any more, except in `test_scalar` (and I don't think thats much of a problem just cos scalars rarely fail their pullbacks are simple).
Instead we use a hack to make `@test` print a message on failure.
and then we plumb that around as needed.
Example of one of the place we would nest a test set before. Mocking up the outer set just for this demo
```julia
julia> @testset "rrule for foo at bar" begin
check_equal(Tangent{Foo}(1, 2), Tangent{Foo}(1, 3))
end
rrule for foo at bar: Test Failed at /Users/oxinabox/JuliaEnvs/ChainRulesWorld/ChainRules.jl/dev/ChainRulesTestUtils/src/check_result.jl:25
Expression: isapprox(actual, expected; kwargs...)
Problem:  Foo.2
Evaluated: isapprox(2, 3)
Stacktrace:
[1] …
```
=> Avoid nesting testsets in test_rule

Project.toml, docs/Manifest.toml, docs/src/index.md, src/testers.jl, test/deprecated.jl, test/testers.jl
Follows up https://github.com/JuliaDiff/ChainRulesCore.jl/pull/358
Breaking because it requires the `dself` to be `NoTangent` rather than `NO_FIELDS`, i.e. `ZeroTangent`.
=> replace `NO_FIELDS` with `NoTangent()`

Project.toml, src/deprecated.jl
Even though we don't have a direct replacement, still good to give a warning.
=> Add deprecation warnings to isapprox

Project.toml, docs/src/index.md, src/testers.jl, test/testers.jl
=> Test the number of outputs in `frule` and `rrule` are correct

docs/src/index.md, src/ChainRulesTestUtils.jl, src/testers.jl, test/runtests.jl
They can also be manually disabled by setting `CHAINRULES_TEST_INFERRED`
to `false`. I have tested that all tests still pass with `JULIA_PKGEVAL`
set to `true`, do we need to test for that by spawning a new Julia
process? Once this is merged, I plan to replace occurences of
`@inferred` in ChainRules with `@maybe_inferred` as well, therefore I
exported that macro.
=> skip `@inferred` tests for PkgEval

Project.toml, docs/Manifest.toml, docs/src/index.md, src/testers.jl, test/testers.jl
=> Make work on functors

Project.toml, src/testers.jl
This was there to prevent overthunking, but fails for some cases where thunking is useful. The instructions on when to thunk are in the docs
=> do not check for thunks

Project.toml, docs/Manifest.toml, docs/make.jl, docs/src/api.md, docs/src/index.md, src/ChainRulesTestUtils.jl, src/check_result.jl, src/rule_config.jl, src/testers.jl, test/testers.jl
Closes #114
Closes #173
To do:
=> test arbitrary functions with `f/rrule`-like API

Project.toml, src/testers.jl
Shortens the testset names for alternative tangents. Did not notice in the original PR since all the tests passed.
=> Shorten testset names

.github/workflows/fix_doctests.yml, Project.toml, docs/Manifest.toml, docs/Project.toml, docs/make.jl, docs/src/index.md, src/testers.jl, test/testers.jl
`∂s` was renamed to `ad_cotangents`, but we missed it in this error message.
So I fixed that and I also changed it to use `test_msg` rather than erroring.
added a test for this case, making sure it failed rather than erroring.
I also changed the length one after to not define a variable called `msg` since that was confusing as to which was meant.
=> fix mistake in non-tuple output message

docs/Manifest.toml, docs/src/api.md, src/ChainRulesTestUtils.jl, src/global_config.jl, src/testers.jl
per @stevengj suggestion here https://github.com/JuliaMath/SpecialFunctions.jl/pull/329#discussion_r658363734
Best to review this one commit at a time
- first commit just moves things
- second commit adds the headline feature
This also resolves #182 since now we can use `unique` as it will be the same function
[Docs Preview](https://juliadiff.org/ChainRulesTestUtils.jl/previews/PR183/api.html#Global-Configuration)
I think we could do with more docs on global config (e.g. re-inference testing) but out of scope for this issue
=> Add public API to enable testing on thunks

Project.toml
To my surprise this didn't break anything. (I tested locally without having 0.10.12 allowed)
=> bump CRC compat

test/rand_tangent.jl
BigFloat length control works badly, we might need a new algorithm.
Either here or in julia
20 is still much shorter than usual.
Normlly BigFloats are >80 characters
=> Relax requirements on printing for BigFloat

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl, test/runtests.jl
- Changed to using ProjectTo for all AbstractArrays (this is a real functional change)
- found that that wasn't compressing all NoTangents: see https://github.com/JuliaDiff/ChainRulesCore.jl/issues/410
- fix that, athen noticed some cases we were not handling that for Tuples/NamedTuples
- fixed those by makign them use the generic struct fallback
=> use ProjectTo for rand_tangent, and also catch some more places we shoud NoTangent

Project.toml, src/finite_difference_calls.jl, src/testers.jl
Needed so that https://github.com/JuliaDiff/FiniteDifferences.jl/pull/189 does not break ChainRules tests
=> Use `NoTangent()` instead of `nothing` to designate non-differentiability

Project.toml, src/ChainRulesTestUtils.jl
This takes the time to run the ChainRules test suite from 52 minutes
down to 40 in my tests. I think there are still more gains to be had
here by playing around a bit with `Experimental.@compiler_options`, but
initially that caused some of the inference tests to fail.
=> don't specialize any functions

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl
Fixes #206 
There were 3 problems:
- `sigdigits` was used rather than `digits` which meant that numbers like `0.0000000000001234` were showing up.
- the `rng` which was in the test to reduce chance of hitting edge cases unexpectedly wasn't used
- that `rng` wasn't initialized so didn't actually serve that purpose anyway
I have now run these tests a few million times, rather than the 50 that is there, and it always passes now.
=> use digits=5 (not sigdigits) to generate nice random numbers.

docs/Manifest.toml, docs/src/index.md
They were written before `rrule_via_ad` was a thing.
=> Improve docs on testing AD gradients

Project.toml, src/testers.jl, test/testers.jl
This is one possible approach to fix https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/217.
An alternative would be to tell users to define `rand_tangent` or, probably better, pass a suitable tangent of type `NotImplemented`. It is a bit inconvenient though since currently we check for equality, including the message AND the LineNumberNodes. I.e., one can't just use `test_rrule(f, x \vdash @not_implemented("does not work"))` since the LineNumberNode would be different from the one used inside the `rrule`. Maybe this should be changed and we should only check if the messages are equal?
=> Allow NotImplemented tangents for things that have a correct tangent of NoTangent

docs/src/index.md, src/testers.jl
I'm not sure if this way of trying to add a reference from https://juliadiff.org/ChainRulesTestUtils.jl/dev/index.html to https://juliadiff.org/ChainRulesTestUtils.jl/dev/api.html#ChainRulesTestUtils.:%E2%8A%A2 is correct, but I found it quite frustrating to see a symbol I've not seen before, with no idea how to type it or what it does - at least a cross-link would be useful to save people from having to read through the source code:)
=> make it easier to find out what ⊢is and how to type it

Project.toml, src/rand_tangent.jl
1. Since https://github.com/JuliaDiff/ChainRulesCore.jl/pull/424/files  `ProjectTo` handles the collapsing of `AbstractArray{NoTangent}` into `NoTangent()`.
2. Further, `ProjectTo(::Array{Float64,0})(::Float64)` handles converting a scalar into a 0 dimensional array.
3. Finally, there is no need for a `collect` since we can make the broadcasting do that (and that might have been specialized by the container and that is fine)
So we can delete all special cases for generating arrays.
This is a minor bump since we are dropping compat with CRC 1.0 and 1.1
I am pretty sure this has no functional change. Though there might be some edge cases.
=> Simply rand_tangent(::AbstractArray)

Project.toml, docs/Manifest.toml, src/finite_difference_calls.jl, test/testers.jl
Currently, arrays of tuples and named tuples as a result from FiniteDifferences are not converted to the correct `Tangent` types. This causes the issue in https://github.com/JuliaMath/ChangesOfVariables.jl/pull/4#discussion_r745556709 and is fixed by this PR (confirmed locally).
~~Deeply nested arrays of (named) tuples will still have an incorrect, so maybe a (better?) alternative would be to always recurse arrays until one hits a `AbstractArray{<:Real}` (which would be returned unmodified, also to avoid copies in this case) or a non-array base case such as `Tuple`, `NamedTuple`, and `Any`.~~
The PR replaces the `_maybe_fix_to_composite` with `ProjectTo`.
It also seems that the function is not tested currently. Should I add some tests?
=> Fix tangent type of arrays of (named) tuples from FD

Project.toml, src/global_checks.jl
Follow up to #228  now that i tried it for real.
I forgot all passing testsets  were show if in same testset as failing one.
Which on real use cases is 1459
```
Test Summary:             | Pass  Fail  Total
ChainRules                | 1529     1   1530
test_helpers.jl         |   69           69
Sensible Constructors   | 1460     1   1461
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1            1
Sensible Constructors |    1 …
```
=> In checking method table don't nest testsets

test/rule_config.jl, test/runtests.jl, test/testers.jl
Just moving ruleconfig tests into a separate file. So that the FD ruleconfig PR will be cleaner
=> move ruleconfig tests into a separate file

src/ChainRulesTestUtils.jl, src/deprecated.jl, src/rule_config.jl, src/testers.jl, test/rule_config.jl, test/testers.jl
Closes https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/241 and https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/221
=> Implement ADviaFDConfig

Project.toml, src/check_result.jl, test/check_result.jl
=> Resolve `test_approx` ambiguities

src/check_result.jl, test/check_result.jl
This fixes the `test_approx()` method call errors in *DistributionsAD.jl* unit tests that I came across while working on TuringLang/DistributionsAD.jl#228.
=> Add ZeroTangent vs array of arrays tests

Project.toml, src/check_result.jl, test/check_result.jl
Correctly pointed out by @devmotion in https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/257/files#r929845299
=> Fix `test_approx` buglets

src/testers.jl, test/testers.jl
Solves #272 
Add a keyword argument "`testset_name`" to `test_scalar`, `test_frule` and `test_rrule` to allow replacing the default name.
It still stays an opt-in option and is mostly useful when `f` is anonymous and its naming is too large to be displayed correctly.
=> Allow editing the testset name

Project.toml, src/testers.jl
#273 broke downstream tests, e.g., in AbstractFFTs, since it broke compatibility with Julia 1.0 (and maybe some other versions as well, I don't remember when `isnothing` was added).
This PR should fix it.
=> Do not use `isnothing` for Julia 1.0 compat

Project.toml, src/ChainRulesTestUtils.jl
Problem is 
the `@test` macro is that it scrubs backtraces to remove stuff from deeper down the stack than the location of the macro, and since `test_rrule` etc use those macros directly the back trace no longer includes the call site in the users tests.
Simple solution is to just stop scrubbing backtraces entirely.
If people like this we could follow up with something more sophisticated.
But lets have that as a seperate PR
This does mean whenever tests are run this warning will show.
```
Testing Running tests...
WARNING: Method definition scrub_backtrace(Any, Any, Any) in module Test at /home/oxinabox/dist/julia-cedar/vanilla/latest/share/julia/stdlib/v1.11/Test/src/Test.jl:89 overwritten at /home/oxinabox/JuliaEnvs/ChainRulesTestUtils.jl/src/ChainRulesTestUtils.jl:26.
Testing …
```
=> Monkey patch Test.scrub_backtrace

docs/make.jl, docs/src/index.md, src/testers.jl
A small PR to help debugging packages once tests fail.
`test_rrule` now indicates which cotangent did not match the finite difference result, which helps to narrow down bugs.
=> added helpful failure massages for tests

.github/workflows/CI.yml, .github/workflows/Documenter.yml, .github/workflows/JuliaNightly.yml, .github/workflows/fix_doctests.yml, src/output_control.jl
ChainRulesTestUtils.jl not work with julia nightly
https://github.com/JuliaMath/AbstractFFTs.jl/actions/runs/14931159549/job/41947508400?pr=139#step:6:160
```
test_frule: fftshift on Vector{Float64},: Error During Test at /home/runner/.julia/packages/ChainRulesTestUtils/Ko1Wr/src/testers.jl:135
Test threw exception
Expression: 
UndefVarError: `eval_test_comparison` not defined in `ChainRulesTestUtils`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
[1] macro expansion
@ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.13/Test/src/Test.jl:727 [inlined]
[2] macro expansion
@ ~/.julia/packages/ChainRulesTestUtils/Ko1Wr/src/testers.jl:135 [inlined]
[3] macro expansion
@ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.13/Test/src/Test.jl:1833 …
```
=> ci: update github actions & fix UndefVarError
